# Generated by Django 4.1.2 on 2022-10-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=1000)),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
    ]
