# Generated by Django 4.1.2 on 2022-10-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
