# Generated by Django 4.1.2 on 2022-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
